spring:
  profiles:
    active: dev #激活开发环境配置
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mengxuegu.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev #开发环境
  application:
    name: cloudDemo01-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8 #开发环境，数据库db01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
    register-with-eureka: true #服务注册开关
    fetch-registry: true #服务发现开关
    service-url: #客户端（服务提供者）注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://localhost:6001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true #访问路径会显示成ip地址

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mengxuegu.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: prod #生产环境
  application:
    name: cloudDemo01-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8 #生产环境，数据库db02
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
    register-with-eureka: true #服务注册开关
    fetch-registry: true #服务发现开关
    service-url: #客户端（服务提供者）注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://localhost:6001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true #访问路径会显示成ip地址

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


